# Personal email - merge at top level so INBOX appears as "INBOX"
Personal_ENABLED="YES"
Personal_BASEURL="http://localhost:3000"
Personal_MERGE="YES"

## More personal email - merge at top level so INBOX appears as "INBOX"
#Personal2_ENABLED="YES"
#Personal2_BASEURL="http://localhost:3000"
#Personal2_MERGE="YES"
#
## Work email - keep namespaced so INBOX appears as "Work/INBOX"
#Work_ENABLED="YES"
#Work_BASEURL="http://localhost:3000"
#Work_MERGE="NO"
